version: '3.9'
services:
  dashboard:
    build: .
    container_name: render_dashboard
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
